Issue 9
gipplab/cs-insights-prediction-endpoint pull request #15
Opened 2022-01-12 17:36 UTC by alexandertv

Implements genericModel and LDAModel with tests.

2022-01-21 11:00 UTC, jpelhaW commented
Please fix merge problems before review.

2022-01-21 11:00 UTC, jpelhaW commented
Please also make sure to merge into dev, not master.

2022-01-22 14:00 UTC, jpelhaW requested changes

2022-01-22 14:00 UTC, jpwahle commented on nlp_land_prediction_endpoint/middleware/auth.py
> +import jwt  # type: ignore
Why do we need to ignore the types of jwt now?

2022-01-22 14:00 UTC, jpwahle commented on .flake8
> +ignore = D104, D205, D415, ANN101, W503
Why are we excluding self annotations? We can just define them for a class and then use the generic type to annotate self.

2022-01-22 14:00 UTC, jpwahle commented on .flake8
> +ignore = D104, D205, D415, ANN101, W503
Please include them again and use the annotations so in the IDEs we get method suggestions etc.

2022-01-22 14:00 UTC, jpelhaW commented on .flake8
> +ignore = D104, D205, D415, ANN101, W503
If you need an example, consider the generic client of the crawler.
https://github.com/ag-gipp/NLPLand/blob/a6f451fdb3d3425df03075e8e3660977e4db502b/nlpland/client/generic/genericclient.py#L10

2022-01-22 22:12 UTC, tom-nslt commented on .flake8
> +ignore = D104, D205, D415, ANN101, W503
I misread this annotation and thought it was soon to be deprecated, like W503 (Binary operators). Now every self is annotated.

2022-01-22 22:16 UTC, tom-nslt commented on nlp_land_prediction_endpoint/middleware/auth.py
> +import jwt  # type: ignore
My mistake, too hastily tried to revert the pipeline "fixes". JWT is no longer ignores as well as requests

2022-02-07 09:01 UTC, jpelhaW approved these changes
LGTM

2022-02-07 09:02 UTC, merged